apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups: [""]
  resources: ["nodes"] # cluster-wide resource can also be namespaced like pods, services, etc.
  verbs: ["get", "list", "describe"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "create"]
