#!/bin/bash

# Author: Alhagie
# Date Create: 10/26/2024
# Date Modified: 10/26/2024

# Description
# Back up files to .tar

# Usage
# ./backuup_script

# Ideas
# - get home directory
# - create a backup folder
# copy home directory files and folders into backup folder

home_dir=$(echo $HOME)
username=$(echo $USER)
current_dir=$(pwd)

echo "Hello ${username^}",
echo "I will now back up your home directory, $home_dir"
echo "You are running this script from ${current_dir}."
echo "Therefore, I will save the backup in ${current_dir}"

tar -cf ${current_dir}/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar $HOME/* 2>/dev/null 

echo "Backup of $current_dir completed successfully"


