apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  strategy: {}
  template:
    metadata:

      labels:
        app: python
    spec:
      containers:
      - image: baicham/python-ingress:v1
        name: nginx
        resources:
          requests:
            cpu: "0.5"
            memory: "128Mi"
          limits:
            cpu: "0.5"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
  name: python
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python
