services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888


  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

# What are the commands to check the status of the kafka cluster?
# docker exec -it kafka bash
# kafka-topics.sh --list --bootstrap-server kafka:9092
# kafka-topics.sh --describe --bootstrap-server kafka:9092 --topic <topic-name>
# kafka-topics.sh --create --bootstrap-server kafka:9092 --topic <topic-name> --partitions <num-partitions> --replication-factor <num-replicas>
# kafka-topics.sh --delete --bootstrap-server kafka:9092 --topic <topic-name>
# kafka-topics.sh --alter --bootstrap-server kafka:9092 --topic <topic-name> --partitions <new-num-partitions>
# kafka-topics.sh --describe --bootstrap-server kafka:9092 --topic <topic-name>

# How to publish messages to a kafka topic with this docker-compose setup?
