apiVersion: v1
kind: Pod
metadata:
  name: nginx-selector
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "0.5"
        memory: 1Gi
      limits:
        cpu: "0.5"
        memory: 1Gi
  nodeSelector:
    kubernetes.io/hostname: kind-control-plane
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
