# Create a pod with an nginx container exposed on port 80. 
# Add a busybox init container which downloads a page using "wget -O /work-dir/index.html http://neverssl.com/online". 
# Make a volume of type emptyDir and 
# mount it in both containers. 
# For the nginx container, mount it on "/usr/share/nginx/html" and 
# for the initcontainer, mount it on "/work-dir". 
# When done, get the IP of the created pod and create a busybox pod and run "wget -O- IP"

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: nginx
spec:
  volumes:
  - name: empty-dir
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: empty-dir
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        cpu: "0.5"
        memory: 1Gi
      limits:
        cpu: "0.5"
        memory: 1Gi
  initContainers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    - -c
    - "wget -O /work-dir/index.html http://neverssl.com/online"
    volumeMounts:
    - name: empty-dir
      mountPath: /work-dir
