apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpa-role
subjects:
- kind: ServiceAccount
  name: hpa-manager-sa
  namespace: default
- kind: User
  name: johndoe
  apiGroup: rbac.authorization.k8s.io
