apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: hpa-manager-sa
  namespace: default
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/my-iam-role  # Map to IAM Role
