apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password # In production, use a Kubernetes Secret instead
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: 500m
              memory: 700Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: my-pvc
        - name: mysql-initdb
          configMap:
            name: mysql-initdb